### ISSUE TITLE
ReactionADCmodel

### ISSUE THREAD

**Issue by he-kadry** [Open-Systems-Pharmacology/PAGE2017-Budapest#1]
Hi, I am working with an ADC model and I tried to import that file but I got this error message. I am trying to couple and ADC with its tox, is there any other way to do that?

Application:
MoBi® 10.0.122

'>' is an unexpected token. The expected token is '='. Line 16, position 76.

Stack trace:
```
at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XElement.ReadElementFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XElement.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XElement.Load(String uri, LoadOptions options)
   at MoBi.Presentation.Tasks.SerializationTask.LoadMany[T](String fileName, Boolean resetIds)
   at MoBi.Presentation.Tasks.Interaction.InteractionTask.LoadItems[T](String filename)
   at MoBi.Presentation.Tasks.Interaction.InteractionTasksForChildren`3.LoadItems(String filename)
   at MoBi.Presentation.Tasks.Interaction.InteractionTasksForChildren`3.adddItemsToProjectFromFile(String filename, TParent parent, IBuildingBlock buildingBlockWithFormulaCache)
   at MoBi.Presentation.Tasks.Interaction.InteractionTasksForChildren`3.AddExisting(TParent parent, IBuildingBlock buildingBlockWithFormulaCache)
   at MoBi.Presentation.UICommand.AddExistingCommandForBase`1.PerformExecute()
   at OSPSuite.Presentation.UICommands.ObjectUICommand`1.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by Yuri05** [comment]
Please make sure to download the *model* file and not the *html* page (click the "Download" button on the page)

**Comment by he-kadry** [comment]
I did. I am trying to load the pkml file

**Comment by he-kadry** [comment]
I downloaded the whole zip file and it is working now. Thanks
